FROM --platform=linux/amd64 python:3.10.5-slim-bullseye as base

COPY ./ /usr/app/dbt

# System setup
RUN apt-get update \
  && apt-get dist-upgrade -y \
  && apt-get install -y --no-install-recommends \
    git \
    ssh-client \
    curl \
    gnupg \
    apt-transport-https \
    software-properties-common \
    make \
    build-essential \
    ca-certificates \
    libpq-dev \
  && apt-get clean \
  && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-cli -y

# Env vars
ENV PYTHONIOENCODING=utf-8
ENV LANG=C.UTF-8

# Set docker basics
WORKDIR /usr/app/dbt/
VOLUME /usr/app

# Update python
RUN python -m pip install --upgrade \
  pip setuptools wheel --no-cache-dir

# Update python && install requirements
RUN python -m pip install --no-cache-dir -r requirements.txt
