name: 'elastic_dbt_duckdb'
version: '1.0.0'
config-version: 2

profile: 'default'

vars:
    "dbt_date:time_zone": "America/Los_Angeles"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  elastic_dbt_duckdb:

