# https://docs.getdbt.com/reference/warehouse-profiles/bigquery-profile
# https://docs.getdbt.com/reference/warehouse-setups/sqlite-setup

config:
    send_anonymous_usage_stats: False

dbt_duckdb:
  outputs:
    dev:
      type: duckdb
      path: '../data/db.duckdb'